# Homebrew packages
brew brew-file
brew git
brew gnu-indent
brew fd
brew fzf
brew jenv
brew lsd
brew pipx
brew pyenv
brew sbt
brew scala
brew starship
brew the_silver_searcher
brew tree
brew --HEAD universal-ctags/universal-ctags/universal-ctags
brew yadm
brew zsh-completion

# Other Cask applications
cask docker

# Nerd Fonts
tap homebrew/cask-fonts
cask font-hack-nerd-font
cask font-inconsolata-nerd-font
cask font-iosevka-nerd-font
cask font-mononoki-nerd-font
